"""
Master Key Setup Utility
Generates and stores master RSA keys for encrypting private keys.
Run this ONCE before first deployment.
"""

import os
import sys
from pathlib import Path
from security.rsa import generate_keys

def generate_master_keys():
    """Generate master RSA key pair for encrypting private keys"""
    print("[*] Generating 2048-bit master RSA key pair...")
    print("    This may take a moment...")
    
    public_key, private_key = generate_keys(2048)
    
    print(f"\n[✓] Master RSA keys generated successfully!")
    print(f"    Public Key:  {public_key}")
    print(f"    Private Key: {private_key}")
    
    return public_key, private_key

def create_env_file():
    """Create or update .env file with master keys"""
    env_path = Path(__file__).parent / '.env'
    
    print(f"\n[*] Setting up .env file at {env_path}")
    
    # Generate master keys
    pub_key, priv_key = generate_master_keys()
    
    # Read existing .env if it exists
    existing_content = ""
    if env_path.exists():
        with open(env_path, 'r') as f:
            existing_content = f.read()
        print("[!] Found existing .env file - updating with master keys...")
    
    # Create or update .env with master keys
    env_content = f"""# CSE447 Lab Project - Environment Configuration
# Generated by setup_encryption.py

# Flask Configuration
FLASK_ENV=development
FLASK_DEBUG=1
SECRET_KEY=your-secret-key-change-this-in-production

# Database
SQLALCHEMY_DATABASE_URI=sqlite:///medlink.db

# Master Encryption Key for Private Keys
# This key encrypts/decrypts all private keys in database
# KEEP THIS SAFE! If compromised, all private keys are exposed!
MASTER_ENCRYPTION_KEY=your-master-key-here-32-hex-characters

# RSA Master Key Pair (for encrypting other private keys)
# Generated by setup_encryption.py - DO NOT MODIFY!
MASTER_RSA_PUBLIC_KEY={pub_key}
MASTER_RSA_PRIVATE_KEY={priv_key}

# Security
SESSION_TIMEOUT=1800
MAX_LOGIN_ATTEMPTS=5
LOCKOUT_DURATION=300

# SMTP (for email verification)
SMTP_SERVER=smtp.gmail.com
SMTP_PORT=587
SMTP_USERNAME=your-email@gmail.com
SMTP_PASSWORD=your-app-password
"""
    
    with open(env_path, 'w') as f:
        f.write(env_content)
    
    print(f"[✓] .env file created/updated successfully!")
    print(f"\n[!] IMPORTANT: Keep the master keys safe!")
    print(f"    Do NOT commit .env to version control!")
    print(f"    Backup these keys securely!")

if __name__ == '__main__':
    try:
        create_env_file()
        print("\n[✓] Master key setup complete!")
        print("[*] You can now run the application - private keys will be encrypted.")
    except Exception as e:
        print(f"\n[!] Error during setup: {e}", file=sys.stderr)
        sys.exit(1)
